//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockWebScraperApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOfStockInfo
    {
        public byte StockId { get; set; }
        public string Symbol { get; set; }
        public string PercentChange { get; set; }
        public string AverageVolume { get; set; }
        public string LastPrice { get; set; }
        public string MarketTime { get; set; }
        public string OpenPrice { get; set; }
        public string HighPrice { get; set; }
        public string LowPrice { get; set; }
        public string YearWeekHigh { get; set; }
        public string YearWeekLow { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual CurrentStockInfo CurrentStockInfo { get; set; }
    }
}
